### ISSUE TITLE
Architecture File

### ISSUE THREAD

**Issue by Jie-su** [rfelixmg/frwgan-eccv18#1]
Hi,

Can I ask where can download the architecture file?

Best Wishes,

Jie,

**Comment by rafafelixphd** [comment]
It is available under src/eccv18/cub/

Regards, Rafa

**Comment by rafafelixphd** [comment]
@Jie-su note that in lastest commits I added the architecture files for all the datasets (CUB, SUN, FLO and AWA1).
src/sota/*
