### ISSUE TITLE
Saving Checkpoints

### ISSUE THREAD

**Issue by naumanbashir70** [rfelixmg/frwgan-eccv18#11]
Hi @rfelixmg ,

Thank you for sharing your valuable code. 
I run src/sota/awa1/train_gan.sh and I am getting error while saving checkpoints. Could you please guide me in solving this. I am using Google Colab
![error](https://user-images.githubusercontent.com/58822992/84951740-4eea7900-b10a-11ea-9ba8-2c57b388cdbc.PNG)
I will appreciate.

**Comment by rafafelixphd** [comment]
@naumanbashir70 you can just comment the line which is performing symlink, and do it manually before running the next batch. You can also copy the weights, instead.

**Comment by naumanbashir70** [comment]
Great!!

Thanks

**Comment by rafafelixphd** [comment]
@naumanbashir70 let me know how it goes, and I can close this issue.

Cheers

**Comment by naumanbashir70** [comment]
Sure, I will let you know.

**Comment by naumanbashir70** [comment]
Hi, @rfelixmg 

I have commented the symlink line, the training completed, I just run it on 20 epoches for GAN just to test that either it will work or not for generate_dataset.sh. 

After completing training  I execute generate_dataset.sh and received error (attached pic.)
The gan-model directory remain empty.

Could you explain this more do **_it manually before running the next batch. You can also copy the weights, instead._**

Thanks,
![image](https://user-images.githubusercontent.com/58822992/85134589-30919400-b256-11ea-93a9-70b99e84b095.png)

**Comment by naumanbashir70** [comment]
@rfelixmg 

Yes, I commented the line performing symlink and it is working fine now. There was no need of manually copying the weights. 
The way you have arranged your code and navigation between them....**Impressive!!!**

**A question and now you can close this issue.**

Why there is need of symlink in you code, If I don't consider the **last_epoch** and other various folders/file saved by symlink like knn.h5, will it affect the performance?

Thanks,

**Comment by rafafelixphd** [comment]
First, tks for your appreciation for the code. I've worked to make it easier and intuitive 😊

Answering your question, I believe it was due to previous version that i've use only the last epoch, and also to make it easier for running manual experiments with the last epoch only. It does not affect the performance. Note that if you want to do experiments in different data sets, you can change the frequency which the checkpoints are made, so you will consider different epochs. Cheers, Rafa
