### ISSUE TITLE
Generated Features

### ISSUE THREAD

**Issue by thecomsian** [rfelixmg/frwgan-eccv18#12]
Hello @rfelixmg 

Thank for providing the Amazing Implementation!!!.

I faced the problem of symlink and solved it  by reading #11 .

I am beginner and I have  some questions.

1. Is there anyway to resume epochs from the point where it is stopped?

2. When I executed, generate_dataset.sh, Output shows, Generating seen and Unseen features and dataset .h5 file is created. How to analyze this H5, How to figure out that unseen feature have been generated, Is there any way to seen them.

Thanks,

**Comment by rafafelixphd** [comment]
@thecomsian tks!

- Is there anyway to resume epochs from the point where it is stopped?

Do you mean re-training\fine-tunning the model? You will find more on --there is a way to re-train or further train the model `[--load_model LOAD_MODEL]`

`python main.py --help`



- When I executed, generate_dataset.sh, Output shows, Generating seen and Unseen features and dataset .h5 file is created. How to analyze this H5, How to figure out that unseen feature have been generated, Is there any way to seen them.


Yes, there is a way to analyse the features generated (bare in mind, they are only resnet features R^{2048}. Hence, they are not highly interpretable.

You can use a software name H5view, which is a free tool that you can find more about here
https://www.neonscience.org/explore-data-hdfview
and here
https://support.hdfgroup.org/products/java/release/download.html

Best wishes, Rafa.
