### ISSUE TITLE
FLO dataset is broken

### ISSUE THREAD

**Issue by yuvval** [rfelixmg/frwgan-eccv18#4]
Thank you for posting your code online. It is really helpful.

I would like to reproduce your results on FLO, however it appears that the soft links under `./data/flo-reed/` are broken, and refer to missing files: 
`data.h5 -> data_TENSORFLOW-CVPR_140318_205157.h5`
`knn.h5 -> FLO_continuous_knn_140318_165701_CVPR.h5`

Could you kindly assist with this issue? 

Note about a minor issue that I fixed on my own: The script `benchmark.sh` looked for the FLO data under `./data/flo` instead of `./data/flo-reed`

Many Thanks,
Yuval

**Comment by rafafelixphd** [comment]
Dear @yuvval ,

You might find flower dataset files at [flower-dataset](https://drive.google.com/file/d/1eTNoqWiBw-vDRLTOOf8nNbc6Uxpq1A8H/view?usp=sharing).

I will fix the link for the previous zip file.

cheers, Rafa

**Comment by rafafelixphd** [comment]
Dear @yuvval 

I have just updated the link for the whole dataset on google drive.
Thanks for pointing out the divergence in the file.

I am closing this issue.
Regards,

**Comment by yuvval** [comment]
Dear Rafa,

Thank you for the reply and for updating the dataset.
I apologize for the later response, as I had few urgent matters this week.

Best, Yuval

**Comment by rafafelixphd** [comment]
Not a problem, you can also hit me up (rafael.felixalves@adelaide.edu.au) in my email if you need any further questions.
