### ISSUE TITLE
Can't reproduce results on FLO, AWA

### ISSUE THREAD

**Issue by yuvval** [rfelixmg/frwgan-eccv18#5]
Hi Rafa,

First, thank you again for making your code available to reproduce the experiments.

I managed to closely get the results on CUB, but I couldn't reproduce the results on FLO or AWA.
On FLO, the problem is that I got really bad results, while on AWA one of the scripts throws an error. For reference, on CUB I got  H=52.6

In more detail: After setting up the environment, according to the instructions in the README, for each dataset I execute the following:

```
source src/sota/<dataset_name>/train_gan.sh
mv ./experiments/sota/<dataset_name>/cycle_wgan/0000_TEST_<TIME>/ ./experiments/sota/<dataset_name>/cycle_wgan/gan-model
source src/sota/<dataset_name>/generate_dataset.sh # and choosing the last epoch to generate feature
source src/sota/<dataset_name>/benchmark.sh
mv ./experiments/sota/<dataset_name>/cycle_wgan/0000_classifier_<TIME>/ ./experiments/sota/<dataset_name>/cycle_wgan/classifier
source src/sota/<dataset_name>/tester.sh

```
For FLO I get the following results: (y(U) =59.7,  y(S) =0, H=0)

For AWA I get the following error when running `tester.sh`:

> FileNotFoundError: [Errno 2] No such file or directory: './experiments/sota/awa1/cycle_wgan/classifier/checkpoint/epoch_80_80/architecture.json'

It looks like some kind of configuration error on the scripts.
Could you kindly assist with this issue?

Many Thanks,
Yuval

**Comment by rafafelixphd** [comment]
Dear @yuvval,

For the AWA errror, have you checked if the file "architecture.json" is on the folder?

Regarding FLO,  can you try to change on generate_dataset.sh

```
_DOMAIN_=[unseen,seen]
_NUM_FEATURES_=[100,100]
```

Cheers, Rafa

**Comment by rafafelixphd** [comment]
Dear @yuvval , there was a typo mistake on the tester.sh file, I've just commit the fix.
