### ISSUE TITLE
code to train cycle_clswgan

### ISSUE THREAD

**Issue by xinw1012** [rfelixmg/frwgan-eccv18#8]
Hi, thanks for the hard work on releasing the code! I'm wondering if there is the code for training the cycle-clswgan. I didn't seem to find it in the repo. Thanks!

**Comment by rafafelixphd** [comment]
Dear @xinw1012,

Thanks for the feedback. We haven't released the cycle-clswgan version -- I'd like to make it available soon. I have been working on something parallell, as soon as I finish I will devote some attention to release this other bit of the model. 

Please, observer that if you make changes on the line 50 of [rwgan.py](https://github.com/rfelixmg/frwgan-eccv18/blob/master/models/rwgan.py) it would be possible to train cycle-clswgan.

Cheers, Rafa.
